# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 13:26
from __future__ import unicode_literals

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('address', models.CharField(blank=True, max_length=64, verbose_name='address')),
                ('id_number', models.CharField(blank=True, default=0, max_length=70, verbose_name='ID number')),
                ('mobile_phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')], verbose_name='mobile phone')),
                ('id_front', models.ImageField(null=True, upload_to=app.models.get_image_path)),
                ('id_back', models.ImageField(null=True, upload_to=app.models.get_image_path)),
                ('selfie_image', models.ImageField(null=True, upload_to=app.models.get_image_path)),
                ('service_image', models.ImageField(null=True, upload_to=app.models.get_image_path)),
                ('user_type', models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Aliado-1', 'Aliado-1'), ('Aliado-2', 'Aliado-2'), ('Aliado-3', 'Aliado-3'), ('Operador', 'Operador'), ('Admin', 'Admin')], max_length=9)),
                ('canBuyDollar', models.BooleanField(default=False)),
                ('coordinatesUsers', models.ManyToManyField(blank=True, related_name='_user_coordinatesUsers_+', to=settings.AUTH_USER_MODEL, verbose_name='Aliados que coordina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=270)),
                ('aba', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountBelongsTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_type', models.CharField(blank=True, choices=[('Origen', 'Origen'), ('Destino', 'Destino')], max_length=8)),
                ('owner', models.CharField(max_length=64, null=True)),
                ('alias', models.CharField(max_length=32, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('id_number', models.IntegerField(null=True, verbose_name='ID number')),
                ('active', models.BooleanField(default=True)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongsTo', to='app.Account')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasAccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('swift', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('allies', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BoxClosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('final_amount', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CanSendTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canSendTo', to='app.Bank')),
                ('target_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canReceiveFrom', to='app.Bank')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('status', models.CharField(choices=[('Pagado', 'Pagado'), ('Por pagar', 'Por pagar'), ('Pagado parcialmente', 'Pagado parcialmente')], max_length=20)),
                ('remaining', models.DecimalField(decimal_places=40, max_digits=40)),
                ('id_allie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('iso_code', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('currency_type', models.CharField(choices=[('FIAT', 'FIAT'), ('Crypto', 'Crypto')], max_length=7)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Exchanger',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ExchangerAccepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_acc', models.DecimalField(decimal_places=15, max_digits=30)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Currency')),
                ('exchanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Exchanger')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('origin_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_currency_pair', to='app.Currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency_pair', to='app.Currency')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPERATION_TIMEOUT', models.IntegerField(verbose_name='Expiración de la operación')),
                ('EMAIL_VALIDATION_EXPIRATION', models.IntegerField(verbose_name='Expiración del email de validación')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=140)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fiat_amount', models.FloatField()),
                ('crypto_rate', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Cancelada', 'Cancelada'), ('Falta verificacion', 'Falta verificacion'), ('Por verificar', 'Por verificar'), ('Verificado', 'Verificado'), ('Fondos por ubicar', 'Fondos por ubicar'), ('Fondos ubicados', 'Fondos ubicados'), ('Fondos transferidos', 'Fondos transferidos')], max_length=20)),
                ('date', models.DateTimeField()),
                ('date_ending', models.DateTimeField()),
                ('exchange_rate', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('account_allie_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_allie_origin', to='app.Account', verbose_name='Cuenta aliado origen')),
                ('account_allie_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_allie_target', to='app.Account', verbose_name='Cuenta aliado origen')),
                ('crypto_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_used', to='app.Currency')),
                ('exchanger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Exchanger')),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_client_origin', to='app.Account')),
                ('id_allie_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_allie_origin', to=settings.AUTH_USER_MODEL, verbose_name='Aliado origen')),
                ('id_allie_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_allie_target', to=settings.AUTH_USER_MODEL, verbose_name='Aliado destino')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to=settings.AUTH_USER_MODEL)),
                ('origin_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_currency_used', to='app.Currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency_used', to='app.Currency')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OperationGoesTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('number_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('operation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goesTo', to='app.Operation')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OperationStateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('original_status', models.CharField(choices=[('Falta verificacion', 'Falta verificacion'), ('Por verificar', 'Por verificar'), ('Verificado', 'Verificado'), ('Fondos por ubicar', 'Fondos por ubicar'), ('Fondos ubicados', 'Fondos ubicados'), ('Fondos transferidos', 'Fondos transferidos')], max_length=20)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changeHistory', to='app.Operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Repurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate', models.FloatField()),
                ('profit', models.FloatField(default=0)),
                ('exchanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Exchanger')),
                ('origin_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_currency_purchase', to='app.Currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency_purchase', to='app.Currency')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RepurchaseCameFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Operation')),
                ('id_repurchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Repurchase')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('code', models.CharField(default=app.models.pkgenTransaction, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('operation_type', models.CharField(choices=[('TO', 'TO'), ('TD', 'TD'), ('TC', 'TC')], max_length=3, verbose_name='Tipo de transacción')),
                ('transfer_image', models.ImageField(upload_to=app.models.get_image_path, verbose_name='Imagen del comprobante')),
                ('amount', models.CharField(max_length=10, verbose_name='Monto')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Currency', verbose_name='Moneda')),
                ('id_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.Operation', verbose_name='Operación asociada')),
                ('origin_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_account', to='app.Account', verbose_name='Cuenta origen')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_account', to='app.Account', verbose_name='Cuenta destino')),
                ('to_exchanger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Exchanger', verbose_name='Exchanger')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='comission',
            name='id_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Operation'),
        ),
        migrations.AddField(
            model_name='boxclosure',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Currency'),
        ),
        migrations.AddField(
            model_name='boxclosure',
            name='exchanger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Exchanger'),
        ),
        migrations.AddField(
            model_name='boxclosure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='app.Country'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Currency'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='repurchasecamefrom',
            unique_together=set([('id_repurchase', 'id_operation')]),
        ),
        migrations.AlterUniqueTogether(
            name='operationgoesto',
            unique_together=set([('operation_code', 'number_account')]),
        ),
        migrations.AlterUniqueTogether(
            name='cansendto',
            unique_together=set([('origin_bank', 'target_bank')]),
        ),
        migrations.AlterUniqueTogether(
            name='boxclosure',
            unique_together=set([('date', 'exchanger', 'currency')]),
        ),
        migrations.AlterUniqueTogether(
            name='accountbelongsto',
            unique_together=set([('id_account', 'id_client')]),
        ),
    ]
