# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='account_allie_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_allie_origin', to='app.Account'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='id_allie_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_allie_origin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='coordinatesUsers',
            field=models.ManyToManyField(related_name='_user_coordinatesUsers_+', to=settings.AUTH_USER_MODEL, verbose_name='Aliados que coordina'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country'),
        ),
    ]
