# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date_ending',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 4, 23, 19, 279540, tzinfo=utc)),
        ),
    ]
