# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 03:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180610_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='allies',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date_ending',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 4, 29, 1, 367181, tzinfo=utc)),
        ),
    ]
