# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180720_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='ally_pay_back',
            field=models.BooleanField(default=False, verbose_name='Aliado transfirió'),
        ),
    ]
