# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-13 18:30
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180512_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=270)),
                ('is_client', models.BooleanField()),
                ('use_type', models.CharField(blank=True, choices=[('Origen', 'Origen'), ('Destino', 'Destino')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='AccountBelongsTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('status', models.CharField(choices=[('Pagado', 'Pagado'), ('Por pagar', 'Por pagar'), ('Pagado parcialmente', 'Pagado parcialmente')], max_length=20)),
                ('remaining', models.DecimalField(decimal_places=40, max_digits=40)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('currency_type', models.CharField(choices=[('FIAT', 'FIAT'), ('Crypto', 'Crypto')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('date', models.DateTimeField()),
                ('origin_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_currency_pair', to='app.Currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency_pair', to='app.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=140)),
                ('country', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fiat_amount', models.DecimalField(decimal_places=40, max_digits=40)),
                ('crypto_rate', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Por verificar', 'Por verificar'), ('Verificado', 'Verificado'), ('Fondos por ubicar', 'Fondos por ubicar'), ('Fondos ubicados', 'Fondos ubicados'), ('Fondos transferidos', 'Fondos transferidos')], max_length=20)),
                ('exchanger', models.CharField(blank=True, max_length=70, null=True)),
                ('date', models.DateTimeField()),
                ('exchange_rate', models.FloatField()),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='OperationGoesTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('operation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Operation')),
            ],
        ),
        migrations.CreateModel(
            name='Repurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate', models.FloatField()),
                ('origin_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_currency_purchase', to='app.Currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency_purchase', to='app.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='RepurchaseCameFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Operation')),
                ('id_repurchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Repurchase')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('operation_type', models.CharField(choices=[('TO', 'TO'), ('TD', 'TD'), ('TE', 'TE')], max_length=3)),
                ('transfer_image', models.ImageField(upload_to=app.models.get_image_path)),
                ('origin_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_account', to='app.Account')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_account', to='app.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='bank',
            name='id',
        ),
        migrations.AddField(
            model_name='bank',
            name='aba',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='swift',
            field=models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Aliado-1', 'Aliado-1'), ('Aliado-2', 'Aliado-2'), ('Aliado-3', 'Aliado-3'), ('Operador', 'Operador'), ('Admin', 'Admin')], max_length=9),
        ),
        migrations.AlterField(
            model_name='bank',
            name='country',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='operation',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operation',
            name='origin_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_currency_used', to='app.Currency'),
        ),
        migrations.AddField(
            model_name='operation',
            name='target_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency_used', to='app.Currency'),
        ),
        migrations.AddField(
            model_name='comission',
            name='id_allie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comission',
            name='id_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Operation'),
        ),
        migrations.AddField(
            model_name='accountbelongsto',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='id_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bank'),
        ),
        migrations.AlterUniqueTogether(
            name='repurchasecamefrom',
            unique_together=set([('id_repurchase', 'id_operation')]),
        ),
        migrations.AlterUniqueTogether(
            name='operationgoesto',
            unique_together=set([('operation_code', 'number_account')]),
        ),
        migrations.AlterUniqueTogether(
            name='accountbelongsto',
            unique_together=set([('id_account', 'id_client')]),
        ),
    ]
