# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180611_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='acceptBanks',
            field=models.ManyToManyField(to='app.Bank'),
        ),
    ]
