# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-16 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180708_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='repurchase',
            name='amount',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='aba',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountbelongsto',
            name='id_number',
            field=models.CharField(blank=True, default=0, max_length=70, null=True, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='accountbelongsto',
            name='owner',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='operation',
            name='crypto_rate',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='operation',
            name='fiat_amount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='operationgoesto',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='repurchase',
            name='profit',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='repurchase',
            name='rate',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_operation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.Operation', verbose_name='Operación asociada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='c@c.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
