# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 01:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bank_acceptbanks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='acceptBanks',
        ),
        migrations.AddField(
            model_name='accountbelongsto',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='allies',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coordinatesUsers',
            field=models.ManyToManyField(blank=True, related_name='_user_coordinatesUsers_+', to=settings.AUTH_USER_MODEL, verbose_name='Aliados que coordina'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Country'),
        ),
    ]
