# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-19 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180513_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_currency', to='app.Currency'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='fiat_amount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
