# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180719_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='ally_pay_back',
            field=models.BooleanField(default=False, verbose_name='Aliado transfirió'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('Cancelada', 'Cancelada'), ('Falta verificacion', 'Falta verificacion'), ('Por verificar', 'Por verificar'), ('Verificado', 'Verificado'), ('Fondos por ubicar', 'Fondos por ubicar'), ('Fondos ubicados', 'Fondos ubicados'), ('Fondos transferidos', 'Fondos transferidos'), ('En reclamo', 'En reclamo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='operationstatechange',
            name='new_status',
            field=models.CharField(choices=[('Falta verificacion', 'Falta verificacion'), ('Por verificar', 'Por verificar'), ('Verificado', 'Verificado'), ('Fondos por ubicar', 'Fondos por ubicar'), ('Fondos ubicados', 'Fondos ubicados'), ('Fondos transferidos', 'Fondos transferidos'), ('En reclamo', 'En reclamo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='operationstatechange',
            name='original_status',
            field=models.CharField(choices=[('Falta verificacion', 'Falta verificacion'), ('Por verificar', 'Por verificar'), ('Verificado', 'Verificado'), ('Fondos por ubicar', 'Fondos por ubicar'), ('Fondos ubicados', 'Fondos ubicados'), ('Fondos transferidos', 'Fondos transferidos'), ('En reclamo', 'En reclamo')], max_length=20),
        ),
    ]
