# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180620_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='accountbelongsto',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='boxclosure',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='cansendto',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='comission',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'default_permissions': (), 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='exchanger',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='exchangeraccepts',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='operationgoesto',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='operationstatechange',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='repurchase',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='repurchasecamefrom',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': ()},
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.Operation'),
        ),
        migrations.AlterField(
            model_name='operationgoesto',
            name='operation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goesTo', to='app.Operation'),
        ),
    ]
