# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-19 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180519_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationgoesto',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
