# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180622_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationstatechange',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Operation'),
        ),
        migrations.AlterField(
            model_name='cansendto',
            name='origin_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canSendTo', to='app.Bank'),
        ),
        migrations.AlterField(
            model_name='cansendto',
            name='target_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canReceiveFrom', to='app.Bank'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(choices=[('TO', 'TO'), ('TD', 'TD'), ('TC', 'TC')], max_length=3),
        ),
    ]
