# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 01:34
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_operationgoesto_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Currency'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='code',
            field=models.CharField(default=app.models.pkgenOperation, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('Falta verificacion', 'Falta verificacion'), ('Por verificar', 'Por verificar'), ('Verificado', 'Verificado'), ('Fondos por ubicar', 'Fondos por ubicar'), ('Fondos ubicados', 'Fondos ubicados'), ('Fondos transferidos', 'Fondos transferidos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default=app.models.pkgenTransaction, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
