# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180622_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_exchanger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Exchanger'),
        ),
        migrations.AlterField(
            model_name='operationstatechange',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='operationstatechange',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changeHistory', to='app.Operation'),
        ),
    ]
