# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180523_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='currency',
        ),
    ]
