# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_bank_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_currency',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.Currency'),
            preserve_default=False,
        ),
    ]
