# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-02 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180628_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPERATION_TIMEOUT', models.IntegerField(verbose_name='Expiración de la operación')),
                ('EMAIL_VALIDATION_EXPIRATION', models.IntegerField(verbose_name='Expiración del email de validación')),
            ],
        ),
    ]
