# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180528_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
