# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-02 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_globalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='fiat_amount',
            field=models.FloatField(),
        ),
    ]
