# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180528_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='id',
        ),
        migrations.AlterField(
            model_name='operation',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
