# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-02 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180702_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default='', verbose_name='Monto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='app.Currency', verbose_name='Moneda'),
            preserve_default=False,
        ),
    ]
