# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-02 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180702_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.CharField(default='0', max_length=10, verbose_name='Monto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='app.Currency', verbose_name='Moneda'),
            preserve_default=False,
        ),
    ]
