# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-08 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180708_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='date_ending',
            new_name='expiration',
        ),
    ]
