# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180716_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationstatechange',
            name='new_status',
            field=models.CharField(choices=[('Falta verificacion', 'Falta verificacion'), ('Por verificar', 'Por verificar'), ('Verificado', 'Verificado'), ('Fondos por ubicar', 'Fondos por ubicar'), ('Fondos ubicados', 'Fondos ubicados'), ('Fondos transferidos', 'Fondos transferidos'), ('Reclamo', 'Reclamo')], default='Por verificar', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationstatechange',
            name='original_status',
            field=models.CharField(choices=[('Falta verificacion', 'Falta verificacion'), ('Por verificar', 'Por verificar'), ('Verificado', 'Verificado'), ('Fondos por ubicar', 'Fondos por ubicar'), ('Fondos ubicados', 'Fondos ubicados'), ('Fondos transferidos', 'Fondos transferidos'), ('Reclamo', 'Reclamo')], max_length=20),
        ),
    ]
